title: Julio Adrián Cedillo
logo: github.png
description: Sociology Student at UC Berkeley
#show_downloads: true
theme: jekyll-theme-minimal
url: "https://www.example.com"
baseurl: ""
nav:
  - title: "Home"
    url: "/"
  - title: "Research Experience"
    url: "/research"
  - title: "CV"
    url: "/CV"
social:
  linkedin: "https://www.linkedin.com/in/jcedi/"
email: "julio.cedillo@berkeley.edu"
